### PR TITLE
Version and style sync across `standard-` repos

### PR DESCRIPTION
**Pull request by mjankowski**
Context: https://github.com/standardrb/standard/pull/658

As described in linked PR, bump some stuff to get a clean, no warnings local run, add simplecov, etc. This one also includes an actions/checkout bump which removes CI warnings.

No issues found w/ standard 1.41.1 bump here.

As noted in linked PR, this one (sorbet) was the only one with remaining warning/deprecation output, which is like:

    warning: `Cop.registry` is deprecated. Use `Registry.global` instead.

These are coming from (and have since been fixed in) `rubocop-sorbet`. We're on 0.7.0, 0.8.7 is current, they were fixed in 0.8.4.

Presumably whenever this is next version bumped and rules contemplated, that warning will go away.

### CODE REVIEW

**Comment by maxveldink** [comment]
@searls Do we have an appetite to look at the latest Sorbet rules and decide which ones we want to incorporate?

**Comment by maxveldink** [comment]
@mjankowski Updating the bundler version is what's causing the 2.7 check to fail. We might want to pull that out of this PR, and think about dropping Ruby 2.7 support in a separate PR.

**Comment by maxveldink** [comment]
Will take a stab in the coming days 👍🏻

**Comment by mjankowski** [comment]
> @mjankowski Updating the bundler version is what's causing the 2.7 check to fail. We might want to pull that out of this PR, and think about dropping Ruby 2.7 support in a separate PR.

Ah, I missed that we had not yet dropped 2.7 in this repo. Updated the PR to remove the bundler version lockfile bump, will watch CI on next run.

I assume (based on linked PR discusssion) that we might WANT to drop 2.7? If so, I can do that as followup here.

**Comment by mjankowski** [comment]
> Updated the PR to remove the bundler version lockfile bump, will watch CI on next run.

I think this needs workflow approval to run.

**Comment by mjankowski** [comment]
Crikey, another CI failure, from `standard-performance` this time.

This time around I rolled all changes back and rebuilt it while actually running 2.7 locally. Maybe that works.

**Pull request merged**
